package ai

import (
	"fmt"
	"strings"
	"unicode/utf8"

	"partybox/backend/internal/models"
)

// ValidateMissions ensures that the missions generated by the model satisfy all
// safety, domain, and database constraints before any database persistence.
func ValidateMissions(missions []GeneratedMission, requestedCount int) error {
	if len(missions) == 0 {
		return fmt.Errorf("%w : aucune mission retournée par l’IA", models.ErrInvalid)
	}

	if requestedCount < 1 {
		return fmt.Errorf("%w : nombre de missions demandé invalide", models.ErrInvalid)
	}
	if len(missions) != requestedCount {
		return fmt.Errorf("%w : nombre de missions générées incorrect (%d reçues, %d attendues)",
			models.ErrInvalid, len(missions), requestedCount)
	}

	for i, m := range missions {
		text := strings.TrimSpace(m.Text)
		if text == "" {
			return fmt.Errorf("%w : texte manquant pour la mission #%d", models.ErrInvalid, i+1)
		}
		runeCount := utf8.RuneCountInString(text)
		if runeCount < 5 || runeCount > 300 {
			return fmt.Errorf("%w : longueur de mission #%d invalide (%d caractères)", models.ErrInvalid, i+1, runeCount)
		}

		category := strings.TrimSpace(m.Category)
		if category == "" {
			return fmt.Errorf("%w : catégorie manquante pour la mission #%d", models.ErrInvalid, i+1)
		}
		catLen := utf8.RuneCountInString(category)
		if catLen < 2 || catLen > 50 {
			return fmt.Errorf("%w : longueur de catégorie invalide pour la mission #%d", models.ErrInvalid, i+1)
		}

		if m.Difficulty < 1 || m.Difficulty > 3 {
			return fmt.Errorf("%w : difficulté invalide (%d) pour la mission #%d, doit être entre 1 et 3",
				models.ErrInvalid, m.Difficulty, i+1)
		}

		if m.Points < 1 || m.Points > 100 {
			return fmt.Errorf("%w : points invalides (%d) pour la mission #%d, doit être entre 1 et 100",
				models.ErrInvalid, m.Points, i+1)
		}
	}

	return nil
}
