CREATE TABLE boxes (
    id text PRIMARY KEY CHECK (id ~ '^[A-Za-z0-9_-]{1,40}$'),
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE games (
    id uuid PRIMARY KEY,
    box_id text NOT NULL REFERENCES boxes(id),
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 60),
    mode text NOT NULL DEFAULT 'secret_missions' CHECK (mode = 'secret_missions'),
    status text NOT NULL DEFAULT 'lobby' CHECK (status IN ('lobby', 'playing', 'ended')),
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    ended_at timestamptz
);
CREATE UNIQUE INDEX one_active_game_per_box ON games(box_id) WHERE status IN ('lobby', 'playing');

CREATE TABLE players (
    id uuid PRIMARY KEY,
    game_id uuid NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 24),
    token_hash text NOT NULL UNIQUE,
    score integer NOT NULL DEFAULT 0 CHECK (score >= 0),
    is_host boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX players_game_idx ON players(game_id);
CREATE UNIQUE INDEX one_host_per_game ON players(game_id) WHERE is_host;
CREATE UNIQUE INDEX player_name_per_game ON players(game_id, lower(name));

CREATE TABLE missions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text text NOT NULL,
    points integer NOT NULL CHECK (points BETWEEN 1 AND 100),
    category text NOT NULL,
    difficulty integer NOT NULL CHECK (difficulty BETWEEN 1 AND 3)
);

CREATE TABLE player_missions (
    id uuid PRIMARY KEY,
    player_id uuid NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    mission_id integer NOT NULL REFERENCES missions(id),
    status text NOT NULL DEFAULT 'assigned' CHECK (status IN ('assigned', 'completed')),
    assigned_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CHECK ((status = 'completed') = (completed_at IS NOT NULL))
);
CREATE UNIQUE INDEX one_current_mission ON player_missions(player_id) WHERE status = 'assigned';
CREATE INDEX player_missions_history_idx ON player_missions(player_id, assigned_at);
